#%RAML 1.0 NamedExample

     
                {
                "productid": 1,
                "categoryid": 13,
                "name": "HP",
                "description": "cor I 5",
                "video_url": "www.HP.com",
                "price": 4000
                }
                  