#%RAML 1.0 Overlay
usage: for Amharic user
extends: new-online-shopping.raml

documentation:
  - title: Introduction
    content: this document craft online shopping rest api raml sepcification

/products:
  description: this is product resource and it will fetch list of products
  
/users:
  description: register users (post users data to rest api)