#%RAML 1.0 ResourceType
post:
  description: <<resourcePathName>> resource created
  responses:
    201:
      body:
        application/json:
          example:
            <<exampleReference1>>
            
          
            